In [111]:
import numpy as np


In [112]:
# creating array using arange function.
a = np.arange(15)   # single dimensional
print(a) 
a = np.arange(15).reshape(3,5) # multi dimensional 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Numpy array properties  

In [113]:
# size of array 
a.size

15

In [114]:
x = np.array([1,2,3,4,5,7,8])
print(x)

[1 2 3 4 5 7 8]


In [115]:
y = np.array([[1,2,3], [2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [116]:
print('shape',x.shape)
print('num of dimension',x.ndim)
print('type of data',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimension',y.ndim)
print('type of dimension',y.dtype)

shape (7,)
num of dimension 1
type of data int32
Y
shape: (2, 3)
num of dimension 2
type of dimension int32


- arange 
- linspace 
- random.*
- eye 
- ones 
- zeros

In [117]:
np.set_printoptions(precision=4, suppress=True)

In [118]:
a = np.arange(-10, 10, .2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [119]:
b = np.linspace(0, 1, 10)
print(b)

[0.     0.1111 0.2222 0.3333 0.4444 0.5556 0.6667 0.7778 0.8889 1.    ]


In [120]:
np.random.random((3,3)) # random values b/w zero to one.


array([[0.4886, 0.4255, 0.7449],
       [0.2388, 0.7795, 0.524 ],
       [0.2191, 0.3997, 0.9375]])

In [121]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end.

array([[861, 972, 614],
       [703, 708, 953],
       [800, 749, 419]])

In [122]:
(np.eye(3, dtype=int)) # identity matrix 
np.rot90(np.eye(3, dtype=int)) # rot90 rotate 

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [123]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [124]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arthimatic 
- statistical
- trigonometric
- logical
- slicing 
- filtering
- sorting


In [125]:
x = np.random.randint(1, 25,(2,3))
y = np.random.randint(1,25,(3,2))
print(x)
print(y)

[[19  1 14]
 [ 8 21 16]]
[[21 11]
 [18 22]
 [ 2 23]]


In [126]:
y.T

array([[21, 18,  2],
       [11, 22, 23]])

In [127]:
print("x+y tansposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

x+y tansposed
[[40 19 16]
 [19 43 39]]
x transposed + y
[[40 19]
 [19 43]
 [16 39]]


In [128]:
print("matrix multiplication elementwise")
print(x * y.T)
print("matrix multiplication")
print(x @ y)

matrix multiplication elementwise
[[399  18  28]
 [ 88 462 368]]
matrix multiplication
[[445 553]
 [578 918]]


In [129]:
np.hstack((x,x,x,x,x))

array([[19,  1, 14, 19,  1, 14, 19,  1, 14, 19,  1, 14, 19,  1, 14],
       [ 8, 21, 16,  8, 21, 16,  8, 21, 16,  8, 21, 16,  8, 21, 16]])

In [130]:
np.vstack((x,x,y.T))

array([[19,  1, 14],
       [ 8, 21, 16],
       [19,  1, 14],
       [ 8, 21, 16],
       [21, 18,  2],
       [11, 22, 23]])

In [131]:
print(x)
print("sum of all elemnets:",x.sum())
print("sum of all elemnets row wise:",x.sum(axis=1))
print("sum of all elemnets col wise:",x.sum(axis=0))
print("average of all elemnets:",x.mean())
print("median of all elemnets:",np.median(x))
print("min of all elemnets:",x.min())
print("max of all elemnets:",x.max())
print("std of all elemnets:",x.std())
print("variance of all elemnets:",x.var())
print("any item in non-zero:",x.any())
print("all item in non-zero:",x.all())

[[19  1 14]
 [ 8 21 16]]
sum of all elemnets: 79
sum of all elemnets row wise: [34 45]
sum of all elemnets col wise: [27 22 30]
average of all elemnets: 13.166666666666666
median of all elemnets: 15.0
min of all elemnets: 1
max of all elemnets: 21
std of all elemnets: 6.8170537787391865
variance of all elemnets: 46.47222222222222
any item in non-zero: True
all item in non-zero: True


In [132]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [133]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.1499  0.8415  0.9906]
 [ 0.9894  0.8367 -0.2879]]
[[ 0.9887  0.5403  0.1367]
 [-0.1455 -0.5477 -0.9577]]
[[ 0.1516  1.5574  7.2446]
 [-6.7997 -1.5275  0.3006]]


In [134]:
# logical
x[x>5] 

array([19, 14,  8, 21, 16])

In [136]:
x = np.random.randint(-3,3 (5,5))
x

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\user\AppData\Local\Temp\ipykernel_7076\3284228177.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  x = np.random.randint(-3,3 (5,5))


TypeError: 'int' object is not callable

In [139]:
x[(x > -2) & (x<2)]

array([1])

## indexing and slicing

In [141]:
x[0, 0]

19

- syntax for slicing in 1d : `[start:stop:step]`
 
- syntax for slicing in 2d:  `[rstart:rstop:rstep, cstart:cstop:cstep]` 

In [146]:
print(x[0]) # first row
print(x[-1]) # last row
print(x[0,:3]) # first row first three elements
# print(x[2,-4:]) # 2 index row last four elements



[19  1 14]
[ 8 21 16]
[19  1 14]


In [150]:

print(x[:, 0]) # first column 
print(x[:, -1]) # last column 
print(x[:,:2]) # first two columns
print(x[:,[1, 2]]) # first index and third index column 
print(x[:, [2,1]]) # 2,1 index column

[19  8]
[14 16]
[[19  1]
 [ 8 21]]
[[ 1 14]
 [21 16]]
[[14  1]
 [16 21]]


In [151]:
x.sort(axis=0)
x

array([[ 8,  1, 14],
       [19, 21, 16]])

In [153]:
x = np.random.randint(1,100, (6,3))
x

array([[39, 31, 48],
       [ 7, 41, 53],
       [67, 94, 82],
       [22, 13, 25],
       [17, 53, 19],
       [70, 14, 84]])

In [155]:
x.sort(axis=0)
x

array([[ 7, 13, 19],
       [17, 14, 25],
       [22, 31, 48],
       [39, 41, 53],
       [67, 53, 82],
       [70, 94, 84]])

In [156]:
x.sort(axis=1)
x

array([[ 7, 13, 19],
       [14, 17, 25],
       [22, 31, 48],
       [39, 41, 53],
       [53, 67, 82],
       [70, 84, 94]])

In [172]:
x = np.array([[2,2,1],[6,5,6],[7,7,9]])
x

array([[2, 2, 1],
       [6, 5, 6],
       [7, 7, 9]])

In [161]:
x.sort(axis=0)
x

array([[2, 2, 1],
       [6, 5, 6],
       [7, 7, 9]])

In [163]:
x.sort(axis=1)
x

array([[1, 2, 2],
       [5, 6, 6],
       [7, 7, 9]])

In [168]:
x = x.flatten()
x.sort()


In [169]:
x

array([1, 2, 2, 5, 6, 6, 7, 7, 9])

In [170]:
x.max()

9

In [176]:
x.argmax() # returns index of max element 

8

In [175]:
x.argmin() # returns index of min element 

2