In [3]:
import numpy as np


In [9]:
# creating array using arange function.
a = np.arange(15)   # single dimensional
print(a) 
a = np.arange(15).reshape(3,5) # multi dimensional 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Numpy array properties  

In [6]:
# size of array 
a.size

15

In [10]:
x = np.array([1,2,3,4,5,7,8])
print(x)

[1 2 3 4 5 7 8]


In [17]:
y = np.array([[1,2,3], [2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [18]:
print('shape',x.shape)
print('num of dimension',x.ndim)
print('type of data',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimension',y.ndim)
print('type of dimension',y.dtype)

shape (7,)
num of dimension 1
type of data int32
Y
shape: (2, 3)
num of dimension 2
type of dimension int32


- arange 
- linspace 
- random.*
- eye 
- ones 
- zeros

In [20]:
np.set_printoptions(precision=4, suppress=True)

In [22]:
a = np.arange(-10, 10, .2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [24]:
b = np.linspace(0, 1, 10)
print(b)

[0.     0.1111 0.2222 0.3333 0.4444 0.5556 0.6667 0.7778 0.8889 1.    ]


In [25]:
np.random.random((3,3)) # random values b/w zero to one.


array([[0.9092, 0.7847, 0.0358],
       [0.3476, 0.5531, 0.657 ],
       [0.5119, 0.3184, 0.7513]])

In [26]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end.

array([[ 68, 756, 536],
       [432, 459, 579],
       [474, 388, 128]])

In [33]:
(np.eye(3, dtype=int)) # identity matrix 
np.rot90(np.eye(3, dtype=int)) # rot90 rotate 

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [29]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arthimatic 
- statistical
- trigonometric
- logical
- slicing 
- filtering
- sorting


In [36]:
x = np.random.randint(1, 25,(2,3))
y = np.random.randint(1,25,(3,2))
print(x)
print(y)

[[14 22 23]
 [20  3 10]]
[[ 3 18]
 [ 9  7]
 [20 19]]


In [37]:
y.T

array([[ 3,  9, 20],
       [18,  7, 19]])

In [38]:
print("x+y tansposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

x+y tansposed
[[17 31 43]
 [38 10 29]]
x transposed + y
[[17 38]
 [31 10]
 [43 29]]


In [39]:
print("matrix multiplication elementwise")
print(x * y.T)
print("matrix multiplication")
print(x @ y)

matrix multiplication elementwise
[[ 42 198 460]
 [360  21 190]]
matrix multiplication
[[700 843]
 [287 571]]


In [40]:
np.hstack((x,x,x,x,x))

array([[14, 22, 23, 14, 22, 23, 14, 22, 23, 14, 22, 23, 14, 22, 23],
       [20,  3, 10, 20,  3, 10, 20,  3, 10, 20,  3, 10, 20,  3, 10]])

In [41]:
np.vstack((x,x,y.T))

array([[14, 22, 23],
       [20,  3, 10],
       [14, 22, 23],
       [20,  3, 10],
       [ 3,  9, 20],
       [18,  7, 19]])

In [43]:
print(x)
print("sum of all elemnets:",x.sum())
print("sum of all elemnets row wise:",x.sum(axis=1))
print("sum of all elemnets col wise:",x.sum(axis=0))
print("average of all elemnets:",x.mean())
print("median of all elemnets:",np.median(x))
print("min of all elemnets:",x.min())
print("max of all elemnets:",x.max())
print("std of all elemnets:",x.std())
print("variance of all elemnets:",x.var())
print("any item in non-zero:",x.any())
print("all item in non-zero:",x.all())

[[14 22 23]
 [20  3 10]]
sum of all elemnets: 92
sum of all elemnets row wise: [59 33]
sum of all elemnets col wise: [34 25 33]
average of all elemnets: 15.333333333333334
median of all elemnets: 17.0
min of all elemnets: 3
max of all elemnets: 23
std of all elemnets: 7.156970184527963
variance of all elemnets: 51.22222222222222
any item in non-zero: True
all item in non-zero: True


In [44]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [45]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.9906 -0.0089 -0.8462]
 [ 0.9129  0.1411 -0.544 ]]
[[ 0.1367 -1.     -0.5328]
 [ 0.4081 -0.99   -0.8391]]
[[ 7.2446  0.0089  1.5882]
 [ 2.2372 -0.1425  0.6484]]
